FROM quay.io/centos/centos:stream9-minimal@sha256:3f9a84c10a4a3fb9fac56ba11c3119759e78abe596e270a1c4e0203547ee80d9
RUN microdnf --setopt=tsflags=nodocs --setopt=install_weak_deps=0 install -y httpd-tools
ENTRYPOINT ["htpasswd", "-Bbn"]
